<!-- GitHub star -->
<a class="github-button" href="https://github.com/{{ config.github }}" data-icon="octicon-star" data-show-count="true" aria-label="Star {{ config.github }} on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/{{ config.github }}/fork" data-icon="octicon-repo-forked" data-show-count="true" aria-label="Fork {{ config.github }} on GitHub">Fork</a><!-- Tweet button -->
<!-- Github Button -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
