<div class="shields-images">
  <a href="https://github.com/go-gorm/gorm/stargazers">
    <img alt="GitHub stars" src="https://img.shields.io/github/stars/go-gorm/gorm?color=1e94de&style=for-the-badge&logo=github">
  </a>

  <a href="https://github.com/go-gorm/gorm/network/members">
    <img alt="GitHub forks" src="https://img.shields.io/github/forks/go-gorm/gorm?color=1e94de&style=for-the-badge&logo=github">
  </a>

  <a href="https://github.com/go-gorm/gorm/graphs/contributors">
    <img alt="GitHub contributors" src="https://img.shields.io/github/contributors/go-gorm/gorm?color=1e94de&style=for-the-badge&logo=github">
  </a>

  <a href="https://github.com/jinzhu">
    <img alt="GitHub followers" src="https://img.shields.io/github/followers/jinzhu?color=1e94de&style=for-the-badge&logo=github">
  </a>

  <a href="https://twitter.com/zhangjinzhu">
    <img alt="Twitter Follow" src="https://img.shields.io/twitter/follow/zhangjinzhu?label=Jinzhu&style=for-the-badge&logo=twitter&logoColor=%23FFF&color=%234494D8">
  </a>

  <a href="/docs/v2_release_note.html">
    <img alt="GitHub tag (latest SemVer)" src="https://img.shields.io/github/v/tag/go-gorm/gorm?label=V2 Release Note&color=red&&style=for-the-badge&logo=go&logoColor=%23FFF">
  </a>
</div>

<style>
  .shields-images img {
    height: 25px;
  }
</style>
